import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import NextAuthSessionProvider from "./SessionProvider";
import AuthGuard from "@/components/AuthGuard";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // Usar useSession solo en client components
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthSessionProvider>
          <Header />
          <AuthGuard>
            <div className="App bg_primary flex min-h-screen pt-24 text-white">
              {children}
            </div>
          </AuthGuard>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
